### ISSUE TITLE
Lint to prevent text before the first heading

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/eipw#115]
Occasionally an author will write something like this:

```markdown
---
eip: 1234
---

This is some text that appears before the first heading. Authors sometimes try
to write an introduction or preface to their proposal here. We don't want to allow
this.

## Abstract

After the "Abstract" heading is the first place we want to allow text.
```

The lint should find _any_ text not included in a section (so essentially just error if it finds text before the first heading.)

**Comment by Abeeujah** [comment]
Hi, I would love to work on this, is there more details to be shared regarding the implementation? or this is all I need to know about the task?

**Comment by SamWilsn** [comment]
@Abeeujah should be good to go! If you have any questions about how anything works, please don't hesitate to ask.

As far as implementation, I'd look at the other files in `eipw-lint/src/lints/markdown` for inspiration.

**Comment by Abeeujah** [comment]
Hi @SamWilsn going through the `eipw-lint/src/lints/markdown/headings_space.rs` file, 
```
let invalid_headings: Vec<_> = ctx
            .body()
            .descendants()
            .filter_map(|node| match &*node.data.borrow() {
                // Collect all matching Text nodes
                Ast {
                    value: NodeValue::Text(text),
                    sourcepos:
                        Sourcepos {
                            start: LineColumn { column: 1, .. }, // Only match text nodes at the start of the line
                            ..
                        },
                    ..
                } => {
                    if let Some(matched_text) = heading_pattern.find(text) {
                        let heading_level = matched_text.end();
                        Some((
                            text.clone(),
                            node.data.borrow().sourcepos.start.line,
                            heading_level,
                        ))
                    } else {
                        None
                    }
                }
                _ => None,
            })
            .collect();
```
This line of code collects all nodes which I'm interpreting to be sections in the `eipw` markdown, if my interpretation is correct, does that mean that any text not in a section is an invalid node, and does that seem to be the solution to this issue?
Whereby if an eip contains invalid node(s) it shouldn't be allowed?

**Comment by Abeeujah** [comment]
Yeah true, but from comrak POV the first node in an eip is the `FrontMatter` 
```
---
eip: 1234
---```
I think this intuition of yours would work if we're checking the second node, and ensuring it's a `Heading`, so far from what I've seen, it might look like this
```rust
match ctx.body().descendants().nth(1) {
NodeValue::Heading => Ok(()),
_ => Err,
}
```

**Comment by SamWilsn** [comment]
That seems reasonable. You can quickly check it by running against some samples from https://github.com/ethereum/EIPs/tree/master/EIPS

**Comment by Abeeujah** [comment]
Tested it against the invalid sample you provided and two other samples from the EIPS repository you provided, both tests pass
![Screenshot_20241031_182406](https://github.com/user-attachments/assets/fa30fbbe-ad0d-488a-b09d-75ca70389df9)

**Comment by Abeeujah** [comment]
Tested it against the invalid sample you provided and two other samples from the EIPS repository you provided, both tests pass
![Screenshot_20241031_182406](https://github.com/user-attachments/assets/fa30fbbe-ad0d-488a-b09d-75ca70389df9)

**Comment by SamWilsn** [comment]
Sounds like you're ready to make a PR then

**Comment by Abeeujah** [comment]
Hi @SamWilsn I've created a PR
