### ISSUE TITLE
Should self-references (`EIP-XXXX` where `XXXX` is the current eip) be allowed?

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/eipw#18]
_Originally posted by @SamWilsn in https://github.com/ethereum/EIPs/pull/5271#discussion_r923588334_

**Comment by Pandapip1** [comment]
No. Use `this EIP` instead.

**Comment by MicahZoltu** [comment]
I weakly prefer `this` and I usually recommend that to authors, but I don't think I have ever blocked an EIP because they used the third person.
