### ISSUE TITLE
preamble-requires-status shouldn't trigger when the status is Withdrawn

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/eipw#38]
`preamble-requires-status` shouldn't trigger when the `status` is `Withdrawn`

_Originally posted by @Pandapip1 in https://github.com/ethereum/EIPs/pull/5381#discussion_r956762576_

**Comment by axic** [comment]
Should this also be lifted for `markdown-link-status`? See the eipw errors on https://github.com/ethereum/EIPs/pull/6414.

**Comment by SamWilsn** [comment]
Definitely, yes.
