### ISSUE TITLE
markdown-link-status should be removed

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/eipw#39]
We are now only considering the status of items that are in the requires header if/when https://github.com/ethereum/EIPs/pull/5614 is merged

**Comment by SamWilsn** [comment]
What? Why?

**Comment by Pandapip1** [comment]
Because we shouldn't be caring about the immutability of EIPs that are referenced for context

**Comment by SamWilsn** [comment]
> as long as their core content doesn't change

There's absolutely nothing preventing an author from completely replacing the content of their EIP while in Draft or Review (nor do I think there should be.)

Links to EIPs that provide context still should follow the same rules as external links: available and immutable. We just get finer grained controls for links within the EIPs repository, so while the current EIP is mutable it can link to other mutable EIPs but when it goes Final so must its links.

**Comment by Pandapip1** [comment]
> There's absolutely nothing preventing an author from completely replacing the content of their EIP while in Draft or Review (nor do I think there should be.)

Fair enough.
