### ISSUE TITLE
New Lint: Space missing in a header

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/eipw#40]
See https://github.com/firnprotocol/EIPs/blob/e7cfd688b622781ab20c0243253f9d330dc350fc/EIPS/eip-5630.md?plain=1#L156 as an example

(Note that if there isn't a space, then it isn't valid markdown)

**Comment by SamWilsn** [comment]
Can the markdown linter do this?

**Comment by Pandapip1** [comment]
> Can the markdown linter do this?

Not AFAIK

**Comment by prampey** [comment]
Hi @SamWilsn is this issue up for grabs?

**Comment by SamWilsn** [comment]
@prampey no one is working on it as far as I know!
