### ISSUE TITLE
New Lint: No top-level headings

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/eipw#42]
I can't find an example, but top-level headings should be disallowed

**Comment by SamWilsn** [comment]
Should be pretty easy to implement. If you create a new lint using a visitor, and override [`enter_heading`](https://github.com/ethereum/eipw/blob/d8d5187f58552e300012efe5d48cfebe86bd9920/eipw-lint/src/tree.rs#L125-L127), you can error if you find a node with the appropriate [`level`](https://docs.rs/comrak/0.14.0/comrak/nodes/struct.NodeHeading.html#structfield.level).

**Comment by Pandapip1** [comment]
This is now handled by the markdown linter.
