### ISSUE TITLE
`eipw` doesn't detect external autolinks

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/eipw#43]
See https://github.github.com/gfm/#autolinks-extension-, https://github.com/firnprotocol/EIPs/blob/e7cfd688b622781ab20c0243253f9d330dc350fc/EIPS/eip-5630.md?plain=1#L158-L161

**Comment by SamWilsn** [comment]
This _should_ be pretty trivial:

Enable the [`autolink`](https://docs.rs/comrak/0.14.0/comrak/struct.ComrakExtensionOptions.html#structfield.autolink) comrak extension here:

https://github.com/ethereum/eipw/blob/d8d5187f58552e300012efe5d48cfebe86bd9920/eipw-lint/src/lib.rs#L654-L656

Then write some tests.
