### ISSUE TITLE
New Lint(s): No colons in title or headings

### ISSUE THREAD

**Issue by Pandapip1** [ethereum/eipw#44]
Example 1: https://github.com/firnprotocol/EIPs/blob/e7cfd688b622781ab20c0243253f9d330dc350fc/EIPS/eip-5630.md?plain=1#L156
Example 2: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-3668.md?plain=1#L3 (sometimes causes issues with front matter parsing)

**Comment by SamWilsn** [comment]
Should be easy enough to modify `preamble::Regex` to apply to all headers by switching `name` to an `Option<&str>` here: 

https://github.com/ethereum/eipw/blob/045316f8e355bc553f8ef7b3912f719e1fc42120/eipw-lint/src/lints/preamble/regex.rs#L20

**Comment by Pandapip1** [comment]
So the issue here is that preamble parsing might error depending on the location of the colon. If so, this error should be caught and the same error message should be provided.
