### ISSUE TITLE
Special case `markdown-rel-links` to help when linking to eips.ethereum.org

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/eipw#5]
For example:

```
Error: error[markdown-rel-links]: non-relative link or image
  --> EIPS/eip-5190.md
   |
17 | This EIP also extends account-bound token from [EIP-4973](https://eips.ethereum.org/EIPS/eip-4973), but the difference is that it can be transferred to other account for mobility between managing device.
   |
   = help: use `./eip-4973.md` instead
```

**Comment by SamWilsn** [comment]
Also do `https://creativecommons.org/publicdomain/zero/1.0/`.

**Comment by JEAlfonsoP** [comment]
I will work on this issue. Ty.

**Comment by JEAlfonsoP** [comment]
Proposal for PR:

Modify `relative_links.rs` to add an `AnnotationType : :Help` to the footer when regex matches:
link && !`link`

**Comment by SamWilsn** [comment]
Changed the example so that it works with other types of links, not just ones of the form `[abc](def)`.

**Comment by Hari-Bombon** [comment]
@SamWilsn can you assign me this repo?

**Comment by SamWilsn** [comment]
I've collected the tests JEAlfonsoP and I came up with over here: https://github.com/ethereum/eipw/tree/issue-5

Might be a good starting place for anyone working on this issue, though I can't promise they're totally up to date.

**Comment by JEAlfonsoP** [comment]
> I've collected the tests JEAlfonsoP and I came up with over here: https://github.com/ethereum/eipw/tree/issue-5
> 
> 
> 
> Might be a good starting place for anyone working on this issue, though I can't promise they're totally up to date.

Anything I can help just let me know. Cheers
