### ISSUE TITLE
Markdown lint for detecting three or more newlines in a row

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/eipw#6]
Example that should fail:

```markdown
Paragraph 1 is this line.


Paragraph 2 is this line.
```

(requested by @pandapip1)

**Comment by JEAlfonsoP** [comment]
Hi, do you want here a: 
Help or Error or Something else ?

**Comment by Pandapip1** [comment]
@JEAlfonsoP this is handled by markdownlint now and this issue can be closed.

**Comment by JEAlfonsoP** [comment]
@Pandapip1 Thank You !, could you if possible take a quick look into the open Issues and comment which could be closed ?
