### ISSUE TITLE
Markdown lint requiring a blank line after section headers

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/eipw#7]
Example that should fail:

```markdown
## This is a header
This text immediately follows the section header without a blank line.
```

(requested by @MicahZoltu)

**Comment by MicahZoltu** [comment]
I'm also OK with no blank line.  Consistency would be nice is all.

**Comment by JEAlfonsoP** [comment]
@Pandapip1 
Is this one handled already ??

**Comment by Pandapip1** [comment]
It's handled by markdownlint.
